version: "3.9"

services:
  db:
    image: postgres:16
    container_name: habeas_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: habeas_tracker
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: